config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get '/signup',    to: 'users#new'
  get '/login/',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 顧客情報更新
  # patch 'users/:user_id/articles/:id/update', to: 'articles#update', as: :update_articles
  # # 顧客情報削除 
  # delete 'users/:user_id/articles/:id/destroy', to: 'articles#destroy', as: :delete_articles
  # 配送計画作成ページ
  # get 'users/:user_id/articles/delivery_plan', to: 'articles#delivery_plan', as: :delivery_plan
  # 配送計画作成
  # patch 'users/:user_id/articles/plan_create', to: 'articles#plan_create', as: :plan_create
  # 配送計画リスト
  # get 'users/:user_id/articles/plan_list', to: 'articles#plan_list', as: :plan_list
  # 拠点情報登録ページ
  # get 'users/:user_id/articles/base_new', to: 'articles#base_new', as: :base_new
  # 拠点情報作成
  # post 'users/:user_id/articles/base_create', to: 'articles#base_create', as: :base_create
  # 拠点情報確認ページ
  # get 'users/:user_id/articles/base_info', to: 'articles#base_info', as: :base_info
  # 拠点情報編集ページ
  # get 'users/:user_id/articles/base_edit', to: 'articles#base_edit', as: :base_edit
  # 拠点情報更新
  # patch  'users/:user_id/articles/base_update', to: 'articles#base_update', as: :base_update
  # 納品開始・終了時間新規保存
  # post 'users/:user_id/articles/plan_list', to: 'daily_reports#delivery_time', as: :delivery_time
  # 日報作成
  patch 'users/:user_id/articles/plan_list', to: 'daily_reports#report_create', as: :report_create
  # 日報一覧
  get 'users/:user_id/daily_reports', to: 'daily_reports#daily_index', as: :daily_index
  # 日報詳細・編集
  get 'users/:user_id/daily_reports/:date', to: 'daily_reports#daily_show', as: :daily_show
  # 日報編集保存
  patch 'users/:user_id/daily_reports/:date/update', to: 'daily_reports#daily_update', as: :daily_update

  
  resources :users do
    # 顧客情報登録
    resources :articles do  #リソースをネストしていることで/users/:user_id/articlesというURLになる。
      collection do
        # 配送計画作成
        get 'delivery_plan', to: 'articles#delivery_plan'
        # 配送計画作成
        patch 'plan_create', to: 'articles#plan_create'
        # 配送計画リスト
        get 'plan_list', to: 'articles#plan_list'
        # 拠点情報登録ページ
        get 'base_new', to: 'articles#base_new'
        # 拠点情報作成
        post 'base_create', to: 'articles#base_create'
        # 拠点情報確認ページ
        get 'base_info', to: 'articles#base_info'
        # 拠点情報編集ページ
        get 'base_edit', to: 'articles#base_edit'
        # 拠点情報更新
        patch 'base_update', to: 'articles#base_update'
        # 納品開始・終了時間新規保存
        post 'plan_list', to: 'daily_reports#delivery_time', as: :delivery_time
      end
    end
  end

end

app/models/article.rb
class Article < ApplicationRecord
  
  belongs_to :user
  has_many :DailyReports, dependent: :delete_all
  geocoded_by :address
  after_validation :geocode
  validates :title, presence: true
  validates :postcode, presence: true, format: { with: /\A\d{3}[-]\d{4}$|^\d{3}[-]\d{2}$|^\d{3}$|^\d{5}$|^\d{7}\z/}
  validates :address, presence: true
  validates :phone_num, presence: true, format: { with: /\A[0-9-]{,14}\z/ }
  
  
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  # ログイン済みでなければ実行できない
  before_action :logged_in_user, only: []
  # 正しいユーザーでなければ実行できない
  before_action :correct_user,   only: [:index, :create, :update, :destroy, :base_new, :base_create,
                                        :base_edit, :base_update, :base_info, :delivery_plan, :plan_list]


  # 顧客一覧
  def index
    @user = User.find(params[:user_id])
    @articles = @user.articles.where.not(base_point: true).order('title')
    @article = @user.articles.new
  end
  
  # 顧客登録
  def create
    @user = User.find(params[:user_id])
    if params[:commit] == "CSVをインポート"
      if params[:users_file].content_type == "text/csv" # file_field_tagで選択したファイルがCSVファイルかどうか
        registered_count = import_articles # import_usersは下の方にメソッドあり CSVのインポート処理関連
        unless @errors.count == 0
          flash[:danger] = "#{@errors.count}件登録に失敗しました"
        end
        unless registered_count == 0
          flash[:success] = "#{registered_count}件登録しました"
        end
        redirect_to user_articles_url(error_users: @errors)
      else
        flash[:danger] = "CSVファイルのみ有効です"
        redirect_to user_articles_url
      end
    else
      @article = @user.articles.build(article_params)
      if @article.save
        flash[:success] = "登録完了"
      else
        flash[:danger] = "登録に失敗しました。"
      end
      redirect_to user_articles_url
    end
  end
  
  # 顧客更新
  def update
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:id])
    if @article.update_attributes(article_params)
      flash[:success] = "登録情報を更新しました。"
    else
      flash[:danger] = "更新に失敗しました。"
    end
      redirect_to user_articles_url
  end
  
  # 顧客削除
  def destroy
    @user = User.find(params[:user_id])
    @article = @user.articles.find(params[:id])
    @article.destroy
    flash[:success] = "削除しました。"
    redirect_to user_articles_url
  end
  
  # 拠点情報新規登録
  def base_new
    @user = User.find(params[:user_id])
    @article = @user.articles.new
  end
  
  # 拠点情報新規作成
  def base_create
    @user = User.find(params[:user_id])
    @article = @user.articles.build(article_params)
    if @article.update_attributes(base_point: true, plan_check: true)
      flash[:success] = "登録完了"
      redirect_to base_info_user_articles_url
    else
      render 'base_new'
    end
  end
  
  # 拠点情報編集
  def base_edit
    @user = User.find(params[:user_id])
    @article = @user.articles.find_by(base_point: true, plan_check: true)
  end
  
  # 拠点情報更新
  def base_update
    @user = User.find(params[:user_id])
    @article = @user.articles.find_by(base_point: true, plan_check: true)
    if @article.update_attributes(article_params)
      flash[:success] = "編集完了"
      redirect_to base_info_user_articles_url
    else
      render 'base_edit'
    end
  end
  
  # 拠点情報
  def base_info
    @user = User.find(params[:user_id])
    @article = @user.articles.find_by(base_point: true, plan_check: true)
  end

  # 配送計画作成ページ
  def delivery_plan
    @user = User.find(params[:user_id])
    @articles = @user.articles.where.not(base_point: true)
  end
  
  # 配送計画作成
  def plan_create
    @user = User.find(params[:user_id])
    @articles = @user.articles.where.not(base_point: true)
    i = 0
    plan_create_params.each do |key, value|
      if value[:plan_check] = true
        i += 1
      end
    end
    
    if params[:commit] == "作成"
      if i <= 20
        plan_create_params.each do |key, value|
          article = Article.find(key)
          article.update_attributes(plan_check: value[:plan_check])
        end
        flash[:success] = "配送計画作成完了"
        redirect_to plan_list_user_articles_url(current_user.id, first_day: Date.today)
      else
        flash[:danger] = "配送先は20箇所までが最大です。"
        redirect_to delivery_plan_user_articles_url(current_user.id)
      end
    elsif params[:commit] == "リセット"
      @articles.update_all(plan_check: false)
      redirect_to delivery_plan_user_articles_url(current_user.id)
    end
  end
  
  # 配送ルート
  def plan_list
      @user = User.find(params[:user_id])
      @articles_all = @user.articles.all
      @articles = @user.articles.where(plan_check: true)
      @articles_count = @user.articles.where(plan_check: true).count
      @article_base = @user.articles.find_by(base_point: true)
      @articles_delivery = @user.articles.where(plan_check: true).where.not(base_point: true)

      # javascriptで使用
      gon.base = @article_base
      gon.count = @articles_count
      gon.articles = @articles
      # latitude = [@article_base.latitude]
      # longitude = [@article_base.longitude]
      latlng = [];
      address = []
      title = []
      
      @articles_delivery.each do |article|
        # latitude.push(article.latitude)
        # longitude.push(article.longitude)
        latlng.push(Geocoder.coordinates(article.address))
        address.push(article.address)
        title.push(article.title)
      end

      # gon.latitude = latitude
      # gon.longitude = longitude
      gon.latlng = latlng
      gon.address = address
      gon.title = title
      
    
    if @article_base == nil
      flash[:danger] = "拠点情報がありません。はじめに拠点情報を登録してください。"
      redirect_to base_new_user_articles_url(current_user.id)
    elsif @articles_delivery.empty?
      flash[:info] = "配送計画を作成して下さい。"
      redirect_to delivery_plan_user_articles_url(current_user.id)
    else

      
      @articles_all.each do |article|
        @first_day = first_day(params[:first_day])
        @last_day = @first_day.end_of_month # 初月の日付を使って月末をインスタンス変数に代
        (@first_day..@last_day).each do |day|
          unless article.DailyReports.any? {|daily| daily.day == day} # unless文なのでfalseの場合、下の処理をする。
            record = article.DailyReports.build(day: day) # Railsの慣習に倣い、あるモデルに関連づいたモデルのデータを生成するのにbuildメソッドを使っている
            record.save
          end
        end
      end
    
    end
  end
  
  private
  
    def article_params
      params.require(:article).permit(:title, :postcode, :address, :phone_num)
    end
    
    def plan_create_params
      params.permit(articles: [:plan_check])[:articles]
    end
    
     # CSVインポート
    def import_articles
      # 登録処理前のレコード数
      current_article_count = ::Article.count
      articles = []
      @errors = []
      # windowsで作られたファイルに対応するので、encoding: "SJIS"を付けている
      # headersオプションを使うと、CSVの初めの1行はheaderとして出力の際に無視される (nameなどの属性名部分)
      CSV.foreach(params[:users_file].path, headers: true) do |row| # CSV.foreach # ファイルから一行ずつ読み込み 又、application.rbでrequire 'csv'も必要
        article = Article.new({ title: row["title"], phone_num: row["phone_num"], postcode: row["postcode"], address: row["address"], user_id: current_user.id})
        if article.valid?
          articles << ::Article.new({ title: row["title"], phone_num: row["phone_num"],postcode: row["postcode"], address: row["address"], user_id: current_user.id})
        else
          @errors << article.errors.inspect # inspectメソッドとは、オブジェクトや配列などをわかりやすく文字列で返してくれるメソッド
        end
      end
      # importメソッドでバルクインサートできる(gem 'activerecord-import'が必要)
      ::Article.import(articles)
      # 何レコード登録できたかを返す
      ::Article.count - current_article_count
    end

    # beforeアクション
    
    # ログイン済みユーザーか確認
    def logged_in_user
      unless logged_in?
        # sessionsヘルパーメソッド
        store_location
        flash[:danger] = "ログインしてください。"
        redirect_to login_url
      end
    end
    
    # 正しいユーザーかどうか確認
    def correct_user
      @user = User.find(params[:user_id])
      # 後付けif文の構成と一緒で、条件式がfalseの場合のみ、冒頭のコードが実行される、current_user?はsessonヘルパーメソッド
        redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/articles_helper.rb
module ArticlesHelper
  

  # 拠点情報があるかどうか
  def bese_point_present?
    @user = User.find(current_user.id)
    @articles = @user.articles.where(base_point: true)
    @articles.present?
  end
  

end

app/views/articles/_base_edit.html.erb
<!-- モーダル・ダイアログ -->
<div class="modal fade" id="edit-form" tabindex="-1" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title">拠点情報編集</h2>
				<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
          <span aria-hidden="true">&times;</span>
        </button>
			</div>


      <div class="modal-body">

        <%= form_for @article, url: base_update_user_articles_path, html: { role: 'form', :id => "form_1" } do |f| %>

          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control validate[required]" %>
          
          <%= f.label :postcode %>
          <%= f.text_field :postcode, class: "form-control validate[required]", id: "postcode" %>
          
          <%= f.label :address %>
          <%= f.text_field :address, class: "form-control validate[required]", id: "address" %>
          
          <%= f.label :phone_num %>
          <%= f.text_field :phone_num, class: "form-control validate[required, custom[phone]]" %>
          
          <%= f.submit "編集", class: "btn btn-success login" %>
          
        <% end %>
    
      </div>
    </div> <!-- modal-content -->
  </div> <!-- modal-dialog -->
</div> <!-- modal fade -->

app/views/articles/_csv.html.erb
<%= form_tag user_articles_path, method: :post, multipart: true do %> <!-- ファイル読み込みの際はmultipart:trueが必要 -->
  <div class="input-group" style="width: 300px;">
    <span class="input-group-btn">
      <!-- onclickはトリガー。この要素をクリックした時に、非表示にしているfile_field_tag(idから)に対してclickイベントを発生させている。
      つまり、ここをクリックすればfile_field_tagのボタンもクリックしたことになり、ファイル選択のダイアログが表示されるようになる。 -->
      <%= button_tag 'ファイル選択', class: "btn btn-default csv_input_btn", type: 'button', onclick: "$('#file_input').click();" %>
    </span>
    <!-- display: noneは非表示になっているだけで機能を無効化してるわけではない。又、required属性で入力を必須にしてエラーが出ないようにしている -->
    <%= file_field_tag 'users_file', id: "file_input", style: "display: none;", onchange: "file_selected($(this));" , required: "required" %>
    <%= text_field_tag 'filename',"", id: "filename", disabled: true, class:"form-control" %>

    <%= submit_tag 'CSVをインポート', style: "width: 300px", class: "btn btn-primary csv_submit" %>
  </div>
<% end %>

<!-- text_field_tagに選択したファイル名を表示させる -->
<script type="text/javascript">
  function file_selected(file_field){
    var filename = $(file_field)[0].files[0].name;
    $("#filename").val(filename);
  }
</script>

app/views/articles/_daily_time.html.erb
<!-- モーダル・ダイアログ -->
<div class="modal fade" id="daily-modal" tabindex="-1" role="dialog">>
	<div class="modal-dialog modal-lg">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title">発着時間</h2>
				<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
          <span aria-hidden="true">&times;</span>
        </button>
			</div>
      <div class="modal-body">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>行き先</th>
              <th>出発</th>
              <th>到着</th>
            </tr>
          </thead>
          
          <tbody>
            <% @articles_delivery.each do |article| %>
              <% daily = article.DailyReports.find_by(day: Date.today) %>
              <tr>
                <td>名称：<%= article.title %><br>所在地：<%= article.address %></td>
                <td>
                  <% if daily.delivery_start.nil? %>
                    <%= button_to "出発", delivery_time_user_articles_path(article_id: article.id), class: "btn btn-success" %>
                  <% else %>
                    <%= daily.delivery_start.strftime("%H時%M分") %>
                  <% end %>
                </td>
                <td>
                  <% if daily.delivery_start.present? && daily.delivery_finish.nil? %>
                    <%= button_to "到着", delivery_time_user_articles_path(article_id: article.id), class: "btn btn-primary" %>
                  <% elsif daily.delivery_finish.present? %>
                    <%= daily.delivery_finish.strftime("%H時%M分") %>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div> <!-- modal-content -->
  </div> <!-- modal-dialog -->
</div> <!-- modal fade -->

app/views/articles/_edit_form.html.erb
<!-- モーダル・ダイアログ -->
<div class="modal fade" id="<%= article.title %>" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title">編集</h2>
				<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
          <span aria-hidden="true">&times;</span>
        </button>
			</div>
			<div class="modal-body">
        <%= form_for article, url: user_article_path(id: article.id), html: { role: 'form', :id => "form_1" } do |f| %>
        
          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control validate[required]" %>
          
          <%= f.label :postcode %>
          <%= f.text_field :postcode, class: "form-control validate[required]", id: "postcode" %>
          
          <%= f.label :address %>
          <%= f.text_field :address, class: "form-control validate[required]", id: "address" %>
          
          <%= f.label :phone_num %>
          <%= f.text_field :phone_num, class: "form-control validate[required, custom[phone]]" %>
          
          <%= f.submit "保存", class: "btn btn-success" %>
          
        <% end %>
      </div>
    </div> <!-- modal-content -->
  </div> <!-- modal-dialog -->
</div> <!-- modal fade -->

app/views/articles/_form.html.erb
<!-- モーダル・ダイアログ -->
<div class="modal fade" id="new-form" tabindex="-1" role="dialog">>
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<h2 class="modal-title">新規登録</h2>
				<button type="button" class="close" data-dismiss="modal" aria-label="閉じる">
          <span aria-hidden="true">&times;</span>
        </button>
			</div>
      <div class="modal-body">
        <%= form_for @article, url: user_articles_path, html: { role: 'form', :id => "form_1" } do |f| %>

          <%= f.label :title %>
          <%= f.text_field :title, class: "form-control validate[required]" %>
          
          <%= f.label :postcode %>
          <%= f.text_field :postcode, class: "form-control validate[required, custom[zip]]", id: "postcode" %>
          
          <%= f.label :address %>
          <%= f.text_field :address, class: "form-control validate[required]", id: "address" %>
          
          <%= f.label :phone_num %>
          <%= f.text_field :phone_num, class: "form-control validate[required, custom[phone]]" %>
          
          <%= f.submit "登録", class: "btn btn-success" %>
          
        <% end %>
      </div>
    </div> <!-- modal-content -->
  </div> <!-- modal-dialog -->
</div> <!-- modal fade -->

app/views/articles/_infowindow.html.erb
<%= javascript_include_tag 'article.js' %> <!-- article.js 読み込み -->


<div id="info-window-name">
  <%= @article.title %><br>
  <%= link_to "Googleマップ", "https://www.google.com/maps/dir/?api=1&destination=#{@article.latitude}, #{@article.longitude}" %>
</div>
<div id="info-wondow-btn">
  <%= button_tag "経路に追加", id: "btn-add", class: "btn btn-primary btn-sm", 
    onclick: "addArticle('#{@article.title}',#{@article.latitude}, #{@article.longitude})" %>
</div>

app/views/articles/base_info.html.erb
<% provide(:title, "拠点情報") %>

<div class="title-name">
  <h1>拠点情報</h1>
</div>

<table class="table table-striped">
  <thead>
    <tr>
      <td>名称：<%= @article.title %></td>
      <td>郵便番号：<%= @article.postcode %></td>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td>所在地：<%= @article.address %></td>
      <td>電話番号：<%= @article.phone_num %></td>
    </tr>
  </tbody>
</table>

<button type="button" class="btn btn-success" data-toggle="modal" data-target="#edit-form">
  編集
</button>
<%= render 'base_edit' %>

<!-- 「起動スクリプト」 -->
<script>

  $(function () {
  	$('#postcode').jpostal({
  		postcode : [
  			'#postcode'
  		],
  		address : {
  			'#address' : '%3%4%5'
  		}
  	});
  });
  
  // jQuery-validate
  $(function(){
      $("#form_1").validationEngine();
  });

</script>

app/views/articles/base_new.html.erb
<% provide(:title, "拠点情報") %>

<div class="title-name">
  <h1>拠点情報登録</h1>
</div>

<div class="row justify-content-center">
  <div class="col-md-6 col-md-offset-3">
    
    <%= form_for @article, url: base_create_user_articles_path, html: { role: 'form', :id => "form_1" } do |f| %>
      <%= render 'shared/article_error_messages', object: @article %>   <!-- 登録失敗時のエラーメッセージ -->
      
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control validate[required]" %>
      
      <%= f.label :postcode %>
      <%= f.text_field :postcode, class: "form-control validate[required]", id: "postcode" %>
      
      <%= f.label :address %>
      <%= f.text_field :address, class: "form-control validate[required]", id: "address" %>
      
      <%= f.label :phone_num %>
      <%= f.text_field :phone_num, class: "form-control validate[required, custom[phone]]" %>
      
      <%= f.submit "登録", class: "btn btn-success login" %>
      
    <% end %>
  </div>
</div>

<!-- 「起動スクリプト」 -->
<script>
$(function () {
	$('#postcode').jpostal({
		postcode : [
			'#postcode'
		],
		address : {
			'#address' : '%3%4%5'
		}
	});
});

$(function(){
    $("#form_1").validationEngine();
});

</script>

app/views/articles/delivery_plan.html.erb
<% provide(:title, "配送計画作成") %>

<div class="title-name">
  <h1>配送計画作成</h1>
</div>

<%= form_tag plan_create_user_articles_path, method: :patch do %>
  <%= submit_tag "リセット", class: "btn btn-secondary reset" %>
  <table class="table table-hover table-bordered">
    <thead class="thead-dark">
      <tr>
        <th>追加</th>
        <th>名称</th>
        <th>郵便番号</th>
        <th>所在地</th>
        <th>電話番号</th>
      </tr>
    </thead>

    <% @articles.each do |article| %>
      <%= fields_for "articles[]", article do |fi| %>
        <tbody>
          <tr>
            <td><%= fi.check_box :plan_check, {}, "true", "false" %></td>
            <td><%= article.title %></td>
            <td><%= article.postcode %></td>
            <td><%= article.address %></td>
            <td><%= article.phone_num %></td>
          </tr>
        </tbody>
      <% end %>
    <% end %>
  </table>
  <% if @articles.present? %>
    <%= submit_tag "作成", class: "btn btn-primary login" %>
  <% end %>
<% end %>

app/views/articles/index.html.erb
<% provide(:title, "顧客リスト") %>


<%= render 'csv' %><br>

<div class="main-contents">
  <div class="base-new">
    <button type="button" class="btn btn-success rounded-circle p-0" data-toggle="modal" data-target="#new-form"
                          aria-expanded="false" aria-controls="collapseExample" style="width:5rem;height:4rem;">
    新規登録
    </button>
    <%= render 'form' %>
  </div>

<table class="table table-hover table-bordered">
  <thead class="thead-dark">
    <tr>
      <th>名称</th>
      <th>郵便番号</th>
      <th>所在地</th>
      <th>電話番号</th>
      <th>編集/削除</th>
    </tr>
  </thead>
  
  <tbody>
    <% @articles.each do |article| %>
      <tr>
        <td><%= article.title %></td>
        <td><%= article.postcode %></td>
        <td><%= article.address %></td>
        <td><%= article.phone_num %></td>
        <td>
          <div class="article-edit">
            <a data-toggle="modal" data-target="#<%= article.title %>" style="cursor: pointer">
            編集
            </a>
            <%= render partial: 'edit_form', locals: {article: article} %><br>
            <%= link_to "削除", user_article_path(id: article, user_id: @user.id), method: :delete, data: {confirm: "削除してよろしいですか？"} %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<script>

  // 郵便番号から住所補完
  $(function () {
  	$('#postcode').jpostal({
  		postcode : [
  			'#postcode'
  		],
  		address : {
  			'#address' : '%3%4%5'
  		}
  	});
  });
  
  // jQuery-validation
  $(function(){
    jQuery("#form_1").validationEngine();
  });
  
  
</script>