config/routes.rb
Rails.application.routes.draw do
  
  root 'static_pages#home'
  get '/signup',    to: 'users#new'
  get '/login/',    to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  
  # 顧客情報更新
  # patch 'users/:user_id/articles/:id/update', to: 'articles#update', as: :update_articles
  # # 顧客情報削除 
  # delete 'users/:user_id/articles/:id/destroy', to: 'articles#destroy', as: :delete_articles
  # 配送計画作成ページ
  # get 'users/:user_id/articles/delivery_plan', to: 'articles#delivery_plan', as: :delivery_plan
  # 配送計画作成
  # patch 'users/:user_id/articles/plan_create', to: 'articles#plan_create', as: :plan_create
  # 配送計画リスト
  # get 'users/:user_id/articles/plan_list', to: 'articles#plan_list', as: :plan_list
  # 拠点情報登録ページ
  # get 'users/:user_id/articles/base_new', to: 'articles#base_new', as: :base_new
  # 拠点情報作成
  # post 'users/:user_id/articles/base_create', to: 'articles#base_create', as: :base_create
  # 拠点情報確認ページ
  # get 'users/:user_id/articles/base_info', to: 'articles#base_info', as: :base_info
  # 拠点情報編集ページ
  # get 'users/:user_id/articles/base_edit', to: 'articles#base_edit', as: :base_edit
  # 拠点情報更新
  # patch  'users/:user_id/articles/base_update', to: 'articles#base_update', as: :base_update
  # 納品開始・終了時間新規保存
  # post 'users/:user_id/articles/plan_list', to: 'daily_reports#delivery_time', as: :delivery_time
  # 日報作成
  patch 'users/:user_id/articles/plan_list', to: 'daily_reports#report_create', as: :report_create
  # 日報一覧
  get 'users/:user_id/daily_reports', to: 'daily_reports#daily_index', as: :daily_index
  # 日報詳細・編集
  get 'users/:user_id/daily_reports/:date', to: 'daily_reports#daily_show', as: :daily_show
  # 日報編集保存
  patch 'users/:user_id/daily_reports/:date/update', to: 'daily_reports#daily_update', as: :daily_update

  
  resources :users do
    # 顧客情報登録
    resources :articles do  #リソースをネストしていることで/users/:user_id/articlesというURLになる。
      collection do
        # 配送計画作成
        get 'delivery_plan', to: 'articles#delivery_plan'
        # 配送計画作成
        patch 'plan_create', to: 'articles#plan_create'
        # 配送計画リスト
        get 'plan_list', to: 'articles#plan_list'
        # 拠点情報登録ページ
        get 'base_new', to: 'articles#base_new'
        # 拠点情報作成
        post 'base_create', to: 'articles#base_create'
        # 拠点情報確認ページ
        get 'base_info', to: 'articles#base_info'
        # 拠点情報編集ページ
        get 'base_edit', to: 'articles#base_edit'
        # 拠点情報更新
        patch 'base_update', to: 'articles#base_update'
        # 納品開始・終了時間新規保存
        post 'plan_list', to: 'daily_reports#delivery_time', as: :delivery_time
      end
    end
  end

end

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light rounded">
    <% if logged_in? %>
      <%= link_to "配送計画システム", user_path(id: current_user.id), class: "navbar-brand" %>
    <% else %>
      <%= link_to "配送計画システム", root_path, class: "navbar-brand" %>
    <% end %>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarsExample09"
            aria-controls="navbarsExample09" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    
      <div class="collapse navbar-collapse" id="navbarsExample09">
        <ul class="navbar-nav mr-auto">
          <% if logged_in? %>
            <li class="nav-item active">
              <%= link_to "トップ", user_path(id: current_user.id), class: "nav-link" %>
              <span class="sr-only">(current)</span>
              <!--<a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>-->
            </li>
            <li class="nav-item">
              <% if bese_point_present? %>
                <%= link_to "拠点情報", base_info_user_articles_path(current_user.id), class: "nav-link" %>
              <% else %>
                <%= link_to "拠点情報", base_new_user_articles_path(current_user.id), class: "nav-link" %>
              <% end %>
            </li>
            <li class="nav-item">
              <%= link_to "顧客リスト", user_articles_path(current_user.id), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "配送計画作成", delivery_plan_user_articles_path(current_user.id), class: "nav-link" %>
            </li>
            <li class="nav-item">
                <%= link_to "配送ルート", plan_list_user_articles_path(current_user.id, first_day: Date.today), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "日報", daily_index_path(current_user.id, first_day: Date.today), class: "nav-link" %>
            </li>
            <li class="nav-item">
              <%= link_to "ログアウト", logout_path, method: :delete, class: "nav-link" %>
            </li>
            <li class="nav-item active">
              <%= link_to "ユーザー名：#{@user.name}", edit_user_path(current_user.id), class: "nav-link" %>
            </li>
          <% else %>
            <li>
              <%= link_to "ログイン", root_path, class: "nav-link" %>
            </li>
            <li>
              <%= link_to "新規登録", signup_path, class: "nav-link" %>
            </li>
          <% end %>
        <ul>
      </div>
  </nav>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    
    <title><%= yield(:title) %></title>

    <%= csrf_meta_tags %>
    
    <%= include_gon %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag 'validationEngine.jquery.css' %> <!-- validationEngine.jquery.css　読み込み -->
    <%= javascript_include_tag 'jquery-3.4.1.min.js' %> <!-- jquery本体 読み込み -->
    <%= javascript_include_tag 'jquery.validationEngine.js' %> <!-- validationEngine本体 読み込み -->
    <%= javascript_include_tag 'jquery.validationEngine-ja.js' %> <!-- 日本語ファイル 読み込み -->
    <%= javascript_include_tag 'jquery.jpostal.js' %> <!-- jquery.jpostal.js 読み込み -->
    
    <%= render 'layouts/shim' %>
    
    <style type="text/css">
      html { height: 100% }
      body { height: 100% }
    </style>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| %>  <!-- flashというオブジェクトを対象にflashハッシュキーとバリュー(keyとvalue)を繰り返し処理をする -->
        <div class="alert alert-<%= message_type %>"><%= message %></div>  <!-- alert- ~ のところはCSSのクラスが動的に変化する。例 alert-sucucess -->
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>